# Bilinen oyuncular için elle girilmiş güç değerleri (Süper Lig ölçeğiyle uyumlu tahminler).
# Anahtar: 'Ad' ya da aynı adlı oyuncuları ayırmak için 'kulüpid:Ad'. Değer: (güç, mevki veya None[, potansiyel])
_RAW = """
psg: Ousmane Dembélé 90 ST; Khvicha Kvaratskhelia 88 LW; Achraf Hakimi 87 RB; Vitinha 88 CM; João Neves 86 CM; Nuno Mendes 87 LB; Marquinhos 84 CB; Willian Pacho 84 CB; Désiré Doué 85 RW 90; Fabián Ruiz 84 CM; Warren Zaïre-Emery 82 CM 88; Matvey Safonov 80 GK; Lucas Chevalier 82 GK; Lucas Hernandez 80 CB; Ferran Torres 82 ST; Lucas Digne 76 LB; Maghnes Akliouche 80 AM; Mika Godts 78 LW; Illia Zabarnyi 81 CB; Dro Fernández 72 AM 86; Senny Mayulu 76 AM 85; Lee Kang-in 81 AM; Gonçalo Ramos 80 ST
bay: Harry Kane 89 ST; Michael Olise 88 RW; Jamal Musiala 88 AM; Joshua Kimmich 87 DM; Luis Díaz 86 LW; Alphonso Davies 83 LB; Dayot Upamecano 84 CB; Jonathan Tah 83 CB; Kim Min-jae 81 CB; Serge Gnabry 80 RW; Manuel Neuer 82 GK; Aleksandar Pavlović 83 DM 88; Lennart Karl 76 AM 88; Tom Bischof 77 CM 85; Konrad Laimer 81 RB; Hiroki Itō 79 LB; Ismael Saibari 81 AM; Nathaniel Brown 80 LB; Jonas Urbig 76 GK 85; Sacha Boey 77 RB; Leon Goretzka 81 CM
rma: Kylian Mbappé 91 ST; Jude Bellingham 88 AM; Vinícius Júnior 89 LW; Federico Valverde 87 CM; Thibaut Courtois 88 GK; Rodrygo 84 RW; Arda Güler 84 AM 89; Dean Huijsen 83 CB 88; Ibrahima Konaté 85 CB; Trent Alexander-Arnold 84 RB; Eduardo Camavinga 83 CM; Aurélien Tchouaméni 84 DM; Antonio Rüdiger 82 CB; Álvaro Carreras 82 LB; Endrick 78 ST 88; Brahim Díaz 80 AM; Denzel Dumfries 82 RB; Bernardo Silva 86 CM; Marc Cucurella 83 LB; Yan Diomande 78 RW 87; Carlos Espí 72 ST 82; Éder Militão 83 CB; Andriy Lunin 78 GK; Franco Mastantuono 76 RW 88; Ferland Mendy 79 LB; Dani Carvajal 80 RB
liv: Alexander Isak 87 ST; Florian Wirtz 86 AM; Alexis Mac Allister 86 CM; Dominik Szoboszlai 86 CM; Virgil van Dijk 85 CB; Alisson Becker 86 GK; Cody Gakpo 84 LW; Hugo Ekitike 84 ST; Jeremie Frimpong 82 RB; Milos Kerkez 81 LB; Ronald Araújo 83 CB; Bradley Barcola 84 LW; Víctor Muñoz 79 LW; Jérémy Jacquet 78 CB 86; Federico Chiesa 78 RW; Rio Ngumoha 72 LW 86; Kostas Tsimikas 77 LB; Joe Gomez 78 CB; Ryan Gravenberch 86 DM; Giorgi Mamardashvili 83 GK; Giovanni Leoni 76 CB 86; Conor Bradley 79 RB; Mohamed Salah 87 RW; Wataru Endo 76 DM; Curtis Jones 81 CM
int: Lautaro Martínez 88 ST; Marcus Thuram 85 ST; Nicolò Barella 86 CM; Alessandro Bastoni 86 CB; Hakan Çalhanoğlu 84 DM; Federico Dimarco 85 LB; Benjamin Pavard 82 CB; Manuel Akanji 84 CB; John Stones 81 CB; Djed Spence 80 RB; Curtis Jones 83 CM; Josep Martínez 80 GK; Pio Esposito 78 ST 87; Henrikh Mkhitaryan 79 AM; Piotr Zieliński 80 CM; Petar Sučić 79 CM 85; Andy Diouf 78 CM; Aleksandar Stanković 76 DM; Ange-Yoan Bonny 78 ST; Davide Frattesi 81 CM; Francesco Acerbi 78 CB; Yann Aurel Bisseck 81 CB; Luis Henrique 79 RW; Carlos Augusto 79 LB
mci: Erling Haaland 91 ST; Rodri 87 DM; Phil Foden 85 AM; Rayan Cherki 85 AM 89; Jérémy Doku 83 LW; Rúben Dias 86 CB; Joško Gvardiol 85 CB; Gianluigi Donnarumma 88 GK; Marc Guéhi 84 CB; Enzo Fernández 85 CM; Elliot Anderson 84 CM 88; Iliman Ndiaye 81 LW; Mateo Kovačić 81 CM; Antoine Semenyo 84 RW; Tijani Reijnders 85 CM; Nico O'Reilly 80 LB 86; Abdukodir Khusanov 78 CB 85; Rico Lewis 79 RB; Ayyoub Bouaddi 74 DM 87; Gerónimo Rulli 77 GK; Matheus Nunes 80 RB; Rayan Aït-Nouri 81 LB; Omar Marmoush 82 ST; Savinho 81 RW; Oscar Bobb 76 RW
ars: Bukayo Saka 88 RW; Declan Rice 88 DM; William Saliba 87 CB; Gabriel Magalhães 87 CB; Martin Ødegaard 86 AM; David Raya 86 GK; Viktor Gyökeres 85 ST; Kai Havertz 83 ST; Eberechi Eze 84 AM; Martín Zubimendi 85 DM; Jurriën Timber 84 RB; Riccardo Calafiori 81 LB; Mikel Merino 82 CM; Noni Madueke 81 RW; Myles Lewis-Skelly 78 LB 87; Kepa Arrizabalaga 78 GK; Cristhian Mosquera 78 CB 85; Piero Hincapié 82 LB; Ben White 81 RB; Ezri Konsa 83 CB; Christos Tzolis 81 LW; Bruno Guimarães 86 CM; Illan Meslier 76 GK; Leandro Trossard 81 LW; Ethan Nwaneri 79 AM 88; Gabriel Martinelli 81 LW; Max Dowman 70 RW 88
bar: Lamine Yamal 90 RW 95; Pedri 88 CM; Raphinha 87 LW; Rodri 87 DM; Dani Olmo 83 AM; Gavi 83 CM; Frenkie de Jong 85 CM; Jules Koundé 85 RB; Pau Cubarsí 84 CB 90; Alejandro Balde 82 LB; João Cancelo 81 RB; Fermín López 83 AM; Joan Garcia 85 GK; Anthony Gordon 83 LW; Gabriel Jesus 79 ST; Karim Adeyemi 81 RW; Dominik Livaković 78 GK; Hamza Abdelkarim 70 ST 82; Eric García 80 CB; Andreas Christensen 79 CB; Marc Casadó 78 DM; Marc Bernal 76 DM 85; Robert Lewandowski 82 ST; Ronald Araújo 83 CB; Marcus Rashford 82 LW; Wojciech Szczęsny 78 GK; Roony Bardghji 74 RW 84
atm: Julián Alvarez 87 ST; Jan Oblak 86 GK; Antoine Griezmann 83 AM; Cristian Romero 85 CB; Giuliano Simeone 81 RW; Marcos Llorente 83 RB; Álex Baena 83 AM; Lee Kang-in 81 AM; Alejandro Grimaldo 83 LB; Jonathan David 82 ST; Alexander Sørloth 81 ST; Ademola Lookman 83 LW; Marc Pubill 78 CB; Koke 80 DM; Robin Le Normand 80 CB; Juan Musso 77 GK; Morten Hjulmand 83 DM; Pablo Barrios 83 CM 87; Obed Vargas 74 DM; David Hancko 82 CB; Nahuel Molina 80 RB; José María Giménez 81 CB; Thiago Almada 81 AM; Johnny Cardoso 80 DM; Conor Gallagher 81 CM; Matteo Ruggeri 78 LB; Nico González 81 LW
bvb: Serhou Guirassy 85 ST; Nico Schlotterbeck 84 CB; Gregor Kobel 85 GK; Jobe Bellingham 79 CM 86; Ethan Nwaneri 79 AM 88; Emre Can 78 DM; Felix Nmecha 82 CM; Marcel Sabitzer 80 CM; Konstantinos Karetsas 74 AM 86; Carney Chukwuemeka 77 AM; Fábio Silva 77 ST; Giannis Konstantelias 76 AM; Julian Ryerson 80 RB; Joey Veerman 79 CM; Waldemar Anton 81 CB; Maximilian Beier 80 ST; Ramy Bensebaini 78 LB; Daniel Svensson 78 LB; Niklas Süle 77 CB; Julian Brandt 81 AM; Karim Adeyemi 81 RW; Pascal Groß 78 CM
rom: Paulo Dybala 81 AM; Nahuel Molina 80 RB; Manu Koné 84 CM; Donyell Malen 81 ST; Rodrigo Mora 76 AM 86; Matías Soulé 82 RW; Lorenzo Pellegrini 79 AM; Leonardo Balerdi 80 CB; Bryan Cristante 79 DM; Santiago Castro 77 ST; Mile Svilar 86 GK; Gianluca Mancini 82 CB; Mario Hermoso 78 CB; Konstantinos Koulierakis 76 CB; Wesley 80 RB; Marten de Roon 76 DM; Evan Ndicka 83 CB; Pierluigi Gollini 72 GK; Angeliño 78 LB; Artem Dovbyk 79 ST; Evan Ferguson 76 ST; Neil El Aynaoui 78 CM
scp: Nestory Irankunda 76 RW 84; Luis Suárez 83 ST; Gonçalo Inácio 83 CB; Maximiliano Araújo 81 LB; Geny Catamo 79 RW; Rodrigo Zalazar 80 AM; Zeno Debast 80 CB; Eduardo Quaresma 79 CB; Rui Silva 81 GK; Iván Fresneda 76 RB; Fotis Ioannidis 79 ST; Sergi Altimira 76 CM; Hidemasa Morita 80 CM; Geovany Quenda 79 RW 88; Jesse Derry 70 LW 82; Pedro Gonçalves 80 AM; Francisco Trincão 81 RW; Morten Hjulmand 83 DM; Ousmane Diomande 83 CB
avl: Alejandro Garnacho 81 LW; Zion Suzuki 80 GK; Emiliano Martínez 85 GK; Nicolas Jackson 81 ST; Leon Goretzka 82 CM; John McGinn 81 CM; Tammy Abraham 79 ST; Ross Barkley 77 AM; Aaron Wan-Bissaka 80 RB; Johan Manzambi 77 CM 86; João Gomes 82 DM; Taylor Harwood-Bellis 78 CB; Victor Lindelöf 78 CB; Matteo Ruggeri 78 LB; Emiliano Buendía 78 AM; Matty Cash 80 RB; Pau Torres 82 CB; Ibrahim Mbaye 72 LW 85; Brian Madjo 68 ST 80; Boubacar Kamara 83 DM; Tyrone Mings 79 CB; Amadou Onana 82 DM; Morgan Rogers 84 AM; Ollie Watkins 83 ST; Youri Tielemans 82 CM; Ian Maatsen 79 LB; Evann Guessand 77 RW
por: Santiago Giménez 82 ST; Diogo Costa 86 GK; André Silva 77 ST; Samu Aghehowa 83 ST 88; Jakub Kiwior 81 CB; Hwang In-beom 79 CM; Seko Fofana 79 CM; Gabri Veiga 81 CM; Victor Froholdt 79 CM 86; Jan Bednarek 79 CB; Pepê 80 RW; Nehuén Pérez 79 CB; Borja Sainz 78 LW; Oskar Pietuszewski 72 LW 86; Alan Varela 82 DM; Pablo Rosario 77 DM; William Gomes 77 RW; Martim Fernandes 78 RB 85; Francisco Moura 80 LB; Rodrigo Mora 76 AM 86; Deniz Gül 72 ST 80; Alberto Costa 77 RB
mun: Marcus Rashford 82 LW; Youri Tielemans 82 CM; Bruno Fernandes 86 AM; Lisandro Martínez 83 CB; Carlos Baleba 81 DM 87; Luke Shaw 78 LB; Mason Mount 79 AM; Andrey Santos 79 CM; Harry Maguire 79 CB; Benjamin Šeško 82 ST 87; Bryan Mbeumo 84 RW; Kobbie Mainoo 80 CM 86; Matheus Cunha 84 LW; Matthijs de Ligt 82 CB; Joshua Zirkzee 77 ST; Senne Lammens 81 GK; Amad Diallo 82 RW; Noussair Mazraoui 79 RB; Leny Yoro 80 CB 87; Diogo Dalot 80 RB; Ayden Heaven 74 CB 84; Manuel Ugarte 79 DM; Casemiro 79 DM; Patrick Dorgu 79 LB; Altay Bayındır 76 GK
bru: Nicolò Tresoldi 76 ST; Yann Sommer 80 GK; Joel Ordóñez 80 CB; Freddie Potts 72 CM; Joaquin Seys 77 LB; Hans Vanaken 81 AM; Carlos Forbs 78 RW; Lee Han-beom 76 CB; Jan Virgili 74 RW; Brandon Mechele 77 CB; Hugo Siquet 76 RB; Hugo Vetlesen 79 CM; Simon Mignolet 78 GK; Raphael Onyedika 80 DM; Aleksandar Stanković 76 DM; Christos Tzolis 81 LW; Ardon Jashari 79 DM; Kyriani Sabbe 76 RB; Chemsdine Talbi 78 RW; Romeo Vermant 72 ST; Nordin Jackers 76 GK
bet: Troy Parrott 79 ST; Héctor Bellerín 78 RB; Antony 82 RW; Dani Ceballos 80 CM; Isco 81 AM; Giovanni Lo Celso 80 AM; Fran García 78 LB; Marc Bartra 75 CB; Abde Ezzalzouli 81 LW; Rodrigo Riquelme 77 LW; Pablo Fornals 81 CM; Cucho Hernández 80 ST; Diego Llorente 77 CB; Junior Firpo 77 LB; Álvaro Fidalgo 77 CM; Álvaro Valles 79 GK; Natan 79 CB; Marc Roca 80 DM; Sofyan Amrabat 79 DM; Aitor Ruibal 76 RB; Ricardo Rodríguez 76 LB; Chimy Ávila 76 ST; Pau López 76 GK
psv: Sergiño Dest 79 RB; Lutsharel Geertruida 78 CB; Filip Kostić 76 LB; Ivan Perišić 77 LW; Ricardo Pepi 78 ST; Ruben van Bommel 78 LW; Esmir Bajraktarević 76 RW; Matěj Kovář 78 GK; Guus Til 81 AM; Paul Wanner 77 AM 85; Kodai Sano 78 DM; Dennis Man 78 RW; Alassane Pléa 75 ST; Sam Lammers 74 ST; Mauro Júnior 77 LB; Jerdy Schouten 81 DM; Yarek Gasiorowski 76 CB 84; Armando Obispo 77 CB; Ryan Flamingo 78 CB; Ismael Saibari 81 AM; Joey Veerman 79 CM; Couhaib Driouech 77 RW; Olivier Boscagli 79 CB
fey: Reiss Nelson 76 LW; Shaqueel van Persie 70 ST 84; Anis Hadj Moussa 80 RW; Jordan Bos 76 LB; Tsuyoshi Watanabe 79 CB; Givairo Read 77 RB 84; Jakub Moder 78 CM; Sem Steijn 79 AM; Jerry St. Juste 76 CB; Luciano Valente 76 AM; Mika Mármol 75 CB; Javi López 74 LB; Gjivai Zechiël 73 CM; Nacho Ferri 73 ST; Tjark Ernst 76 GK; Oussama Targhalline 76 DM; Gonçalo Borges 74 RW; Charles Vanhoutte 76 DM; Timon Wellenreuther 79 GK; Quinten Timber 78 CM; Gernot Trauner 78 CB; Hugo Bueno 76 LB; Cyle Larin 76 ST
lil: Ethan Mbappé 70 CM 80; Ayase Ueda 79 ST; Olivier Giroud 74 ST; Orlando Gill 74 GK; Nabil Bentaleb 77 CM; Calvin Verdonk 75 LB; Tanguy Nianzou 76 CB; Nathan Ngoy 77 CB; Dilane Bakwa 78 RW; Hákon Haraldsson 79 AM; Hamza Igamane 76 ST; Romain Perraud 77 LB; Berke Özer 78 GK; Alexsandro 81 CB; Ngal'ayel Mukau 76 CM 84; Osame Sahraoui 75 RW; Maurits Kjærgaard 73 AM; Tiago Santos 77 RB; Aïssa Mandi 76 CB; Benjamin André 79 DM; Chancel Mbemba 78 CB; Thomas Meunier 76 RB; Hamza Igamane 76 ST; Félix Correia 74 RW
nap: Kevin De Bruyne 84 AM; Rasmus Højlund 82 ST; Scott McTominay 86 CM; Benoît Badiashile 78 CB; Billy Gilmour 80 DM; Noa Lang 80 LW; Vanja Milinković-Savić 81 GK; David Neres 81 RW; Frank Anguissa 83 CM; Giovanni Di Lorenzo 82 RB; Alex Meret 81 GK; Leonardo Spinazzola 77 LB; Stanislav Lobotka 84 DM; Lorenzo Lucca 78 ST; Amir Rrahmani 81 CB; Matteo Politano 80 RW; Mathías Olivera 81 LB; Antonio Vergara 72 AM; Alessandro Buongiorno 83 CB; Sam Beukema 81 CB; Romelu Lukaku 80 ST; Miguel Gutiérrez 81 LB
rbl: Christopher Nkunku 81 ST; Marc Guiu 74 ST 83; Antonio Nusa 80 LW 87; David Raum 82 LB; Ørjan Nyland 74 GK; Castello Lukeba 83 CB 87; Neil El Aynaoui 78 CM; Christoph Baumgartner 81 AM; Johan Bakayoko 80 RW 85; Assan Ouédraogo 76 CM 86; Nicolas Seiwald 79 DM; Willi Orbán 79 CB; Brajan Gruda 78 AM 85; Maxime Estève 77 CB; Lukas Klostermann 77 CB; Ridle Baku 79 RB; Benjamin Henrichs 76 RB; Maarten Vandevoordt 78 GK 85; Xaver Schlager 80 CM; Rômulo 76 ST; Kosta Nedeljković 76 RB; Yan Diomande 78 RW 87; El Chadaille Bitshiabu 73 CB
vil: Georges Mikautadze 80 ST; Nicolas Pépé 80 RW; Renato Veiga 80 CB; Alex Freeman 75 RB; Ayoze Pérez 79 ST; Juan Foyth 80 RB; Nathan Saliba 72 CM; Tajon Buchanan 78 RW; Pape Gueye 80 DM; Gerard Moreno 79 ST; Péter Gulácsi 76 GK; Tani Oluwaseyi 74 ST; Logan Costa 79 CB; Ilias Akhomach 74 RW; Alberto Moleiro 79 AM 85; Santiago Mouriño 77 CB; Carlos Romero 76 LB; Luiz Júnior 80 GK; Dani Parejo 79 CM; Santi Comesaña 79 CM; Sergi Cardona 78 LB; Rafa Marín 79 CB; Thomas Partey 80 DM
stu: Deniz Undav 82 ST; Ermedin Demirović 80 ST; Angelo Stiller 84 CM; Bilal El Khannouss 79 AM; Jamie Leweling 80 RW; Dženan Pejčinović 72 ST; Maximilian Mittelstädt 81 LB; Leo Sauer 72 RW 83; Dan-Axel Zagadou 78 CB; Josha Vagnoman 76 RB; Grischa Prömel 78 CM; Chris Führich 79 LW; Finn Jeltsch 78 CB 86; Atakan Karazor 78 DM; Tiago Tomás 76 ST; Jeff Chabot 79 CB; Luca Jaquez 76 CB; Fabian Bredlow 73 GK; Alexander Nübel 82 GK; Ameen Al-Dakhil 76 CB; Ramon Hendriks 77 LB; Lorenz Assignon 76 RB; Nikolas Nartey 75 CM
lev: Jarell Quansah 81 CB; Facundo Medina 80 LB; Moussa Diaby 82 RW; Malik Tillman 82 AM; Patrik Schick 83 ST; Victor Boniface 80 ST; Guéla Doué 76 RB; Lucas Vázquez 77 RB; Ibrahim Maza 79 AM 87; Aleix García 82 CM; Miguel Gutiérrez 81 LB; Edmond Tapsoba 82 CB; Christian Kofane 74 ST 84; Robert Andrich 79 DM; Loïc Badé 80 CB; Nathan Tella 76 RW; Mark Flekken 79 GK; Equi Fernández 81 DM; Martin Terrier 78 LW; Ernest Poku 77 RW; Janis Blaswich 76 GK; Arthur 76 RB; Exequiel Palacios 82 CM
ben: Jhon Durán 79 ST; João Palhinha 83 DM; Claudio Echeverri 77 AM 87; Clément Lenglet 78 CB; Andreas Schjelderup 80 LW; Gianluca Prestianni 76 RW 85; Vangelis Pavlidis 82 ST; Alessandro Circati 76 CB; Dodi Lukébakio 81 RW; Anatoliy Trubin 83 GK; Rafa Silva 78 AM; Enzo Barrenechea 79 DM; Fredrik Aursnes 81 CM; Tomás Araújo 81 CB; Heorhiy Sudakov 80 AM; Jakub Kamiński 77 LW; Souffian El Karouani 76 LB; Leandro Barreiro 78 CM; Nicolás Otamendi 79 CB; Samuel Dahl 77 LB; Richard Ríos 80 CM; Franjo Ivanović 76 ST; António Silva 80 CB
juv: Nick Woltemade 81 ST; Randal Kolo Muani 81 ST; Kenan Yıldız 86 LW 90; Kerim Alajbegović 72 AM 85; Guglielmo Vicario 84 GK; Pape Matar Sarr 81 CM; Douglas Luiz 79 CM; Weston McKennie 80 CM; Francisco Conceição 82 RW; Zeki Çelik 77 RB; Manuel Locatelli 83 DM; Arkadiusz Milik 76 ST; Teun Koopmeiners 80 AM; Jhon Lucumí 81 CB; Kamil Grabara 77 GK; Khéphren Thuram 83 CM; Lloyd Kelly 79 CB; Bremer 84 CB; Pierre Kalulu 81 CB; Andrea Cambiaso 82 LB; Federico Gatti 80 CB; Dušan Vlahović 82 ST; Jonathan David 82 ST; Edon Zhegrova 81 RW; Juan Cabal 77 LB; Michele Di Gregorio 81 GK
mil: Christian Pulisic 84 RW; Gonçalo Ramos 80 ST; Adrien Rabiot 83 CM; Mike Maignan 87 GK; Luka Modrić 81 CM; Fikayo Tomori 80 CB; Diego Moreira 76 RW; Ruben Loftus-Cheek 79 CM; Samuel Chukwueze 77 RW; Omari Hutchinson 76 RW; Pervis Estupiñán 79 LB; Alphadjo Cisse 70 CM 83; Yunus Musah 78 CM; Francesco Camarda 72 ST 85; Alexis Saelemaekers 81 RB; Mario Gila 81 CB; Strahinja Pavlović 81 CB; Ardon Jashari 79 DM; Matteo Gabbia 79 CB; Samuele Ricci 79 DM; Youssouf Fofana 80 DM; Santiago Giménez 82 ST; Koni De Winter 78 CB; Christopher Nkunku 81 ST; Zachary Athekame 74 RB
lyo: Nicolás Tagliafico 78 LB; Loïs Openda 81 ST; Keito Nakamura 79 LW; Corentin Tolisso 80 CM; Ruben Kluivert 76 LB; Pavel Šulc 79 AM; Tyler Morton 77 DM; Ernest Nuamah 76 RW; Julien Duranville 74 LW; Tanner Tessmann 77 CM; Moussa Niakhaté 81 CB; Zachary Athekame 74 RB; Mads Bidstrup 74 CM; Abner 76 LB; Dominik Greif 78 GK; Rémy Descamps 72 GK; Felix Bacher 72 CB; Clinton Mata 78 RB; Malick Fofana 80 LW 87; Afonso Moreira 75 RW; Adam Karabec 76 AM; Rayan Cherki 85 AM
azk: Mateo Chávez 76 LB; Kees Smit 76 CM 87; Calvin Stengs 77 AM; Wesley Hoedt 76 CB; Jordy Clasie 75 DM; Peer Koopmeiners 77 CM; Jizz Hornkamp 74 ST; Weslley Patati 73 RW; Mexx Meerdink 74 ST; Seiya Maikuma 76 RB; Ro-Zangelo Daal 73 LW; Rion Ichihara 72 CB; Wouter Goes 75 CB; Rome-Jayden Owusu-Oduro 77 GK 84; Jeroen Zoet 71 GK; Sven Mijnans 78 AM; Troy Parrott 79 ST; Denso Kasius 76 RB
oly: Leon Bailey 78 RW; Armando González 74 ST; Gustavo Puerta 77 CM; Stefan Ortega 81 GK; Ayoub El Kaabi 81 ST; Remo Freuler 79 DM; Roman Yaremchuk 77 ST; Marcus Pedersen 76 RB; Gelson Martins 79 RW; Gustavo Sá 77 CM; Yusuf Yazıcı 76 AM; Jota Silva 76 RW; Nair Tiknizyan 75 LB; Kostas Fortounis 75 AM; David Carmo 77 CB; Joel Roca 72 LW; Panagiotis Retsos 77 CB; Manolis Saliakas 76 RB; Chiquinho 79 AM; Christos Mouzakitis 77 CM 86; Santiago Hezze 78 DM; Konstantinos Tzolakis 79 GK; Lorenzo Pirola 77 CB; Zinedin Smajlović 72 CB; Daniel Podence 79 LW; Rodinei 76 RB; Francisco Ortega 75 LB
rso: Mikel Oyarzabal 83 ST; Takefusa Kubo 82 RW; Héctor Fort 74 RB 83; Mamadou Sarr 72 CB; Luka Sučić 79 CM; Carlos Soler 79 CM; Gonçalo Guedes 77 LW; Sergio Gómez 78 LB; Álvaro Odriozola 76 RB; Álex Remiro 82 GK; Orri Óskarsson 76 ST; Ander Barrenetxea 78 LW; Jon Martín 76 CB 84; Arsen Zakharyan 77 AM; Yangel Herrera 79 CM; Jon Aramburu 77 RB; Beñat Turrientes 77 CM; Igor Zubeldia 80 CB; Brais Méndez 80 AM; Duje Ćaleta-Car 78 CB; Aihen Muñoz 75 LB; Jon Gorrotxategi 76 CM
om: Pierre-Emile Højbjerg 82 DM; Timothy Weah 78 RB; Neal Maupay 76 ST; Angel Gomes 79 CM; Igor Paixão 80 LW; Emerson Palmieri 78 LB; Amine Gouiri 81 ST; Nayef Aguerd 81 CB; Geoffrey Kondogbia 78 DM; Derek Cornelius 77 CB; CJ Egan-Riley 76 CB; Amine Harit 78 AM; Keyliane Abdallah 70 RW; Jeffrey de Lange 76 GK; Ulisses Garcia 75 LB; Himad Abdelli 76 CM; Tochukwu Nnadi 73 DM; Faris Moumbagna 74 ST; Mason Greenwood 83 RW; Pierre-Emerick Aubameyang 78 ST; Benjamin Pavard 81 CB; Matt O'Riley 79 CM; Hamed Junior Traorè 77 AM; Arthur Vermeeren 77 CM
ren: Brice Samba 82 GK; Charlie Cresswell 76 CB; Esteban Lepaul 78 ST; Musa Al-Taamari 78 RW; Boulaye Dia 77 ST; Sebastian Szymański 80 AM; Eliezer Mayenda 72 ST; Przemysław Frankowski 77 RB; Bryan Reynolds 75 RB; Adrien Thomasson 77 CM; Abdelhamid Aït Boudlal 74 CB; Valentin Rongier 77 CM; Ludovic Blas 78 AM; Alidu Seidu 75 CB; Quentin Merlin 76 LB; Arnaud Nordin 74 LW; Djaoui Cissé 73 CM; Mahdi Camara 76 DM; Breel Embolo 78 ST; Anthony Rouault 76 CB; Lilian Brassier 76 CB
cry: Ben Chilwell 76 LB; Ismaïla Sarr 81 RW; Dean Henderson 82 GK; Takehiro Tomiyasu 77 CB; Yéremy Pino 80 RW; Jean-Philippe Mateta 81 ST; Axel Disasi 78 CB; Adam Wharton 82 DM 88; Dwight McNeil 77 LW; Quinten Timber 76 CM; Anan Khalaili 72 RB; Eddie Nketiah 75 ST; Daichi Kamada 79 CM; Óscar Mingueza 78 RB; Honest Ahanor 72 CB 84; Jørgen Strand Larsen 78 ST; Evann Guessand 77 RW; Chris Richards 79 CB; Jefferson Lerma 78 DM; Tyrick Mitchell 79 LB; Borna Sosa 75 LB; Walter Benítez 77 GK
bou: Alex Scott 78 CM 85; Justin Kluivert 81 AM; Rayan 74 RW 85; Eli Junior Kroupi 74 ST 85; Tyler Adams 80 DM; António Silva 80 CB; Marcus Tavernier 80 LW; Ben Gannon-Doak 74 RW; Max Aarons 74 RB; Julián Araujo 77 RB; Michele Di Gregorio 81 GK; Álvaro Rodríguez 70 ST; Đorđe Petrović 80 GK; Adrien Truffert 79 LB; Juanlu Sánchez 76 RB; Evanilson 79 ST; Ryan Christie 78 CM; Lewis Cook 78 DM; James Hill 75 CB; David Brooks 76 RW; Bafodé Diakité 79 CB; Veljko Milosavljević 72 CB 84; Amine Adli 78 RW
rcv: Borja Iglesias 79 ST; Altay Bayındır 76 GK; Marcos Alonso 76 LB; Ilaix Moriba 77 CM; Couhaib Driouech 77 RW; Sebastián Cáceres 76 CB; Iago Aspas 76 ST; Carl Starfelt 77 CB; Ferran Jutglà 76 ST; Ionuț Radu 77 GK; Williot Swedberg 77 LW; Javi Galán 74 LB; Abdoulaye Faye 72 CB; Javi Rodríguez 75 CB; Iván Villar 72 GK; Aleix Febas 73 CM; Javi Rueda 74 RB; Fran Beltrán 78 CM; Hugo Álvarez 76 LW; Pablo Durán 76 ST; Óscar Mingueza 78 RB
hof: Andrej Kramarić 79 AM; Ozan Kabak 78 CB; Fisnik Asllani 78 ST; Adam Hložek 79 ST; Vladimír Coufal 76 RB; Nathan De Cat 70 CM 83; Oliver Baumann 81 GK; Patrick Wimmer 76 RW; Adam Daghim 72 LW; Kōki Machida 76 CB; Robin Hranáč 77 CB; Bernardo 76 LB; Alexander Prass 76 LB; Wouter Burger 78 DM; Leon Avdullahu 76 DM; Max Moerstedt 71 ST; Tim Lemperle 76 ST; Grischa Prömel 78 CM; Bazoumana Touré 74 LW
ata: Franck Kessié 80 CM; Charles De Ketelaere 83 AM; Eljif Elmas 79 AM; Sead Kolašinac 78 CB; Jonathan Rowe 77 LW; Gianluca Scamacca 80 ST; Mario Pašalić 80 AM; Giacomo Raspadori 80 ST; Giorgio Scalvini 81 CB 86; Nicola Zalewski 78 LW; Kamaldeen Sulemana 77 RW; Odilon Kossounou 79 CB; Marco Carnesecchi 83 GK; Raoul Bellanova 80 RB; Lazar Samardžić 79 AM; Davide Zappacosta 77 RB; Isak Hien 82 CB; Nikola Krstović 78 ST; Éderson 83 CM; Berat Djimsiti 80 CB; Marten de Roon 76 DM; Yunus Musah 78 CM
bra: Pau Víctor 76 ST; João Moutinho 75 CM; Ricardo Horta 80 AM; Jonas Wind 76 ST; Gustaf Lagerbielke 76 CB; Jovan Milošević 72 ST; Fran Navarro 76 ST; Adrian Bajrami 73 CB; Bright Arrey-Mbi 75 CB; Denis Huseinbašić 74 CM; Víctor Gómez 76 RB; Demir Ege Tıknaz 75 DM 84; Sikou Niakaté 76 CB; Adrian Barišić 75 LB; Mario Dorgeles 75 CM; Tiago Sá 74 GK; Jean-Baptiste Gorby 76 CM; Amine El Ouazzani 76 ST; Lukáš Horníček 76 GK; Rodrigo Zalazar 80 AM; Gabri Martínez 76 RW
aja: Marc-André ter Stegen 83 GK; Julian Brandt 81 AM; Sofyan Amrabat 79 DM; Tolu Arokodare 76 ST; Kasper Dolberg 78 ST; Daley Blind 75 CB; Simon Adingra 76 LW; Marcos Leonardo 74 ST; Thilo Kehrer 77 CB; Davy Klaassen 76 CM; Viktor Tsyhankov 77 RW; Oscar Gloukh 77 AM; Maarten Paes 75 GK; Caio Henrique 77 LB; Steven Berghuis 76 RW; Jofre Torrents 70 LB; Owen Wijndal 72 LB; Youri Baas 78 CB 84; Anton Gaaei 76 RB; Kenneth Taylor 78 CM; Mika Godts 78 LW; Jorthy Mokio 76 CB 86; Josip Šutalo 78 CB; Remko Pasveer 74 GK; Oliver Edvardsen 75 RW
scf: Igor Matanović 76 ST; Matthias Ginter 80 CB; Yuito Suzuki 76 AM; Vincenzo Grifo 78 LW; Philipp Lienhart 78 CB; Mio Backhaus 75 GK; Christian Günter 76 LB; Maximilian Eggestein 79 CM; Niklas Beste 77 LW; Derry Scherhant 73 RW; Yannik Engelhardt 74 DM; Florian Müller 76 GK; Lucas Höler 75 ST; Florent Muslija 74 AM; Patrick Osterhage 76 CM; Lukas Kübler 77 RB; Johan Manzambi 77 CM 86; Noah Atubolu 81 GK; Junior Adamu 75 ST; Philipp Treu 76 RB; Jordy Makengo 75 LB
asm: Folarin Balogun 79 ST; Ansu Fati 76 LW; Lamine Camara 79 CM 86; Eric Dier 77 CB; Takumi Minamino 80 AM; Aleksandr Golovin 79 AM; Denis Zakaria 82 DM; Paris Brunner 72 AM; Mika Biereth 78 ST; Lukas Hradecky 78 GK; Mohammed Salisu 80 CB; Vanderson 80 RB; Matthis Abline 76 ST; Jordan Teze 77 CB; Philipp Köhn 77 GK; Eliesse Ben Seghir 78 LW 85; Paul Pogba 76 CM; Thilo Kehrer 77 CB; Caio Henrique 77 LB; Krépin Diatta 77 RW; Christian Mawissa 75 CB 84; Soungoutou Magassa 76 DM
bha: Luka Vušković 76 CB 88; Yankuba Minteh 79 RW 85; Promise David 74 ST; Evan Ferguson 76 ST; Kaoru Mitoma 81 LW; Malick Yalcouyé 72 CM 83; Jason Steele 72 GK; Jack Hinshelwood 77 CM; Maxim De Cuyper 77 LB; Yasin Ayari 78 CM; Ferdi Kadıoğlu 80 LB; Diego Gómez 78 CM; Bart Verbruggen 81 GK; Pascal Groß 78 CM; Lewis Dunk 78 CB; Charalampos Kostoulas 72 ST 84; Pascal Struijk 76 CB; Mats Wieffer 78 CM; Georginio Rutter 79 AM; Igor Julio 77 CB; Jan Paul van Hecke 80 CB; Carlos Baleba 81 DM 87; Joël Veltman 74 RB; Solly March 76 RW; Stefanos Tzimas 74 ST 84; Tom Watson 70 LW 83; Diego Coppola 75 CB; Olivier Boscagli 79 CB
che: Emiliano Martínez 85 GK; Morgan Rogers 84 AM; Valentín Barco 77 LB; Cole Palmer 86 AM; Danny Welbeck 76 ST; João Pedro 83 ST; Maxence Lacroix 81 CB; Jordan Henderson 76 CM; Reece James 84 RB; Pedro Neto 83 RW; Malo Gusto 81 RB; Marco Palestra 76 RB 85; Moisés Caicedo 88 DM; Estêvão 83 RW 90; Roméo Lavia 80 DM; Pep Chavarría 76 LB; Mike Penders 72 GK 84; Wesley Fofana 80 CB; Levi Colwill 83 CB; Trevoh Chalobah 81 CB; Robert Sánchez 80 GK; Jorrel Hato 78 LB 86; Jamie Gittens 79 LW; Alejandro Garnacho 81 LW; Liam Delap 78 ST; Enzo Fernández 85 CM; Andrey Santos 79 CM; Facundo Buonanotte 76 AM; Dário Essugo 75 DM; Mamadou Sarr 72 CB
tot: Mykhailo Mudryk 76 LW; Omar Marmoush 82 ST; Pedro Porro 83 RB; Richarlison 78 ST; Sandro Tonali 85 DM; Andy Robertson 80 LB; Tosin Adarabioyo 77 CB; Marcos Senesi 80 CB; Xavi Simons 83 AM; Mateus Fernandes 79 CM; James Maddison 81 AM; Dominic Solanke 80 ST; Conor Gallagher 80 CM; Lucas Bergvall 79 CM 87; Sávio 83 RW; Jan Paul van Hecke 80 CB; Micky van de Ven 84 CB; Mathys Tel 76 LW 85; Mohammed Kudus 83 RW; Antonín Kinský 77 GK 84; Rodrigo Bentancur 79 CM; Destiny Udogie 80 LB; Kevin Danso 79 CB; Dejan Kulusevski 82 RW; Pape Matar Sarr 81 CM; Archie Gray 76 CM 86; Djed Spence 80 RB; João Palhinha 83 DM; Randal Kolo Muani 81 ST; Brennan Johnson 80 RW; Guglielmo Vicario 84 GK; Wilson Odobert 76 LW
new: Nico González 82 DM; Matias Fernandez-Pardo 76 ST 84; Anthony Elanga 80 RW; Amar Dedić 80 RB; Yoane Wissa 81 ST; Lewis Hall 81 LB 86; Dan Burn 78 CB; Lukáš Horníček 76 GK; Harvey Barnes 79 LW; Bazoumana Touré 74 LW; Joe Willock 77 CM; Nick Pope 81 GK; Joelinton 81 CM; Aladji Bamba 70 CM; William Osula 75 ST; Malick Thiaw 81 CB; Tino Livramento 81 RB; Sean Steur 68 AM 82; Fabian Schär 79 CB; Sven Botman 81 CB; Jacob Murphy 79 RW; Aaron Ramsdale 78 GK; Lewis Miley 76 CM 85; Nick Woltemade 81 ST; Jacob Ramsey 78 CM; Kieran Trippier 77 RB; Sandro Tonali 85 DM
whu: Jarrod Bowen 82 RW; Manor Solomon 76 LW; Edson Álvarez 79 DM; Joël Piroe 77 ST; Arne Engels 76 CM; Taty Castellanos 78 ST; Joël Veltman 74 RB; Alphonse Areola 78 GK; Tomáš Souček 79 CM; Konstantinos Mavropanos 77 CB; Maxwel Cornet 72 LW; Kyle Walker-Peters 77 RB; Morato 75 CB; Maximilian Kilman 78 CB; Mads Hermansen 78 GK; Adama Boiro 70 LB; Lucas Paquetá 82 AM; El Hadji Malick Diouf 77 LB; Soungoutou Magassa 76 DM; Crysencio Summerville 78 RW; Niclas Füllkrug 76 ST; Callum Wilson 75 ST; Aaron Wan-Bissaka 80 RB; Mateus Fernandes 79 CM
eve: Jack Grealish 81 LW; Jordan Pickford 84 GK; Ainsley Maitland-Niles 73 RB; Brennan Johnson 80 RW; Christian Nørgaard 79 DM; Tyrique George 74 LW; Thierno Barry 77 ST; Kiernan Dewsbury-Hall 79 CM; James Tarkowski 80 CB; James Garner 80 CM; Michael Keane 77 CB; Jarrad Branthwaite 80 CB 85; Hayden Hackney 76 CM; Vitalii Mykolenko 78 LB; Tyler Dibling 74 RW 84; Harrison Armstrong 72 CM 82; Charly Alcaraz 76 AM; Jake O'Brien 78 CB; Idrissa Gueye 77 DM; Tim Iroegbunam 74 DM; Iliman Ndiaye 81 LW; Dwight McNeil 77 LW; Beto 76 ST; Nathan Patterson 75 RB; Carlos Alcaraz 76 AM; Merlin Röhl 74 CM
ful: Gonzalo García 77 ST 85; Alex Iwobi 79 RW; Oscar Bobb 76 RW; Sander Berge 80 DM; Emile Smith Rowe 78 AM; Ryan Sessegnon 76 LB; Josh King 72 CM 82; Antonee Robinson 80 LB; César Palacios 70 CM; Shea Charles 74 DM; Kenny Tete 77 RB; Hugo Larsson 78 CM 85; Calvin Bassey 79 CB; Bernd Leno 81 GK; Timothy Castagne 76 RB; Jonah Kusi-Asare 70 ST 80; David Affengruber 74 CB; Joachim Andersen 79 CB; Rodrigo Muniz 78 ST; Harry Wilson 79 RW; Saša Lukić 77 CM; Tom Cairney 74 CM; Raúl Jiménez 76 ST; Adama Traoré 76 RW; Samuel Chukwueze 77 RW; Kevin 74 LW
nfo: Liam Delap 78 ST 85; Ousmane Diomande 83 CB 87; Morgan Gibbs-White 83 AM; Daniel Muñoz 82 RB; Neco Williams 79 LB; Xaver Schlager 80 CM; James McAtee 77 AM; Chris Wood 78 ST; Callum Hudson-Odoi 79 LW; Dan Ndoye 80 RW; Ibrahim Sangaré 78 DM; Ola Aina 79 RB; Igor Jesus 77 ST; Nikola Milenković 82 CB; Arnaud Kalimuendo 78 ST; Murillo 81 CB; Nicolás Domínguez 78 CM; Ryan Yates 76 DM; Matz Sels 81 GK; Elliot Anderson 84 CM; Douglas Luiz 79 CM; Omari Hutchinson 76 RW; Nicolò Savona 76 RB; Oleksandr Zinchenko 76 LB; John Victor 77 GK
sev: Robbie Ure 70 ST; Rubén Vargas 78 LW; Odysseas Vlachodimos 77 GK; Youssouf Fofana 79 CM; Giorgi Kochorashvili 76 CM; Gabriel Suazo 76 LB; Lucas Stassin 76 ST 84; Fran González 70 GK; Chidera Ejuke 77 RW; Marcão 78 CB; Lucien Agoumé 78 DM; Jon Guridi 75 CM; Isaac Romero 76 ST; Arouna Sangante 74 CB; Félix Correia 74 RW; Kike Salas 77 CB; Juan Iglesias 76 RB; Julio Díaz 70 LB; José Ángel Carmona 77 RB; Djibril Sow 78 CM; César Azpilicueta 75 RB; Alexis Sánchez 74 ST; Nemanja Gudelj 77 DM; Akor Adams 76 ST; Batista Mendy 76 DM; Tanguy Nianzou 76 CB
val: Harvey Elliott 80 AM; José Gayà 78 LB; Arnaut Danjuma 77 LW; Guido Rodríguez 78 DM; Pablo Maffeo 76 RB; Umar Sadiq 75 ST; Kayne van Oevelen 70 GK; Stole Dimitrievski 79 GK; Javi Guerra 79 CM 85; Aliou Dieng 72 CM; Arnau Martínez 76 RB; Mouctar Diakhaby 77 CB; Hugo Duro 78 ST; Diego López 77 RW; Pepelu 77 DM; Justin de Haas 70 CB; Dimitri Foulquier 73 RB; César Tárrega 78 CB 84; André Almeida 77 CM; Luis Rioja 76 RW; Julen Agirrezabala 77 GK; Filip Ugrinić 76 AM; Largie Ramazani 75 LW; Jesús Vázquez 74 LB
ath: Nico Williams 84 LW; Unai Simón 84 GK; Aymeric Laporte 81 CB; Iñaki Williams 80 RW; Oihan Sancet 82 AM; Dani Vivian 81 CB; Álex Padilla 72 GK; Álvaro Djaló 74 LW; Johaneko Louis-Jean 70 RB; Maroan Sannadi 74 ST; Gorka Guruzeta 78 ST; Yeray Álvarez 79 CB; Álex Berenguer 78 RW; Yuri Berchiche 75 LB; Aitor Paredes 78 CB; Robert Navarro 76 RW; Mikel Jauregizar 79 CM 86; Nico Serrano 72 LW; Mikel Vesga 77 CM; Óscar de Marcos 74 RB; Iñigo Ruiz de Galarreta 79 CM; Beñat Prados 78 CM; Iñigo Lekue 74 RB; Jesús Areso 77 RB; Unai Gómez 74 AM
laz: Romano Floriani Mussolini 70 RB; Davide Frattesi 81 CM; Josip Šutalo 78 CB; Albert Guðmundsson 80 AM; Nuno Tavares 80 LB; Kenneth Taylor 78 CM; Mattia Zaccagni 81 LW; Diogo Leite 76 CB; Andrea Pinamonti 76 ST; Alfonso Pedraza 78 LB; Danilho Doekhi 77 CB; Matteo Cancellieri 75 RW; Christos Mandas 78 GK 84; Luca Pellegrini 74 LB; Nicolò Rovella 81 DM; Gustav Isaksen 78 RW; Adam Marušić 77 RB; Fisayo Dele-Bashiru 74 CM; Alessio Romagnoli 80 CB; Ivan Provedel 81 GK; Matteo Guendouzi 81 CM; Mario Gila 81 CB; Tijjani Noslin 76 ST; Pedro 76 LW; Toma Bašić 75 CM; Reda Belahyane 74 CM; Samuel Gigot 76 CB
fio: Franco Mastantuono 76 RW 88; David de Gea 83 GK; Beto 76 ST; Radu Drăgușin 78 CB; Wilfried Gnonto 77 RW; Pedro Gonçalves 80 AM; Álex Jiménez 76 RB; João Mário 74 RB; Dodô 81 RB; Nicolò Fagioli 79 CM; Cher Ndour 76 CM; Marin Pongračić 78 CB; Luca Ranieri 78 CB; Moise Kean 82 ST; Rolando Mandragora 79 CM; Pietro Comuzzo 78 CB 85; Simon Sohm 76 CM; Robin Gosens 78 LB; Albert Guðmundsson 80 AM; Edin Džeko 75 ST; Fabiano Parisi 76 LB; Hans Nicolussi Caviglia 76 CM; Oliver Christensen 74 GK
bol: Artem Dovbyk 79 ST; Federico Bernardeschi 78 RW; Lewis Ferguson 81 CM; Arthur Theate 79 CB; Juan Miranda 78 LB; Riccardo Orsolini 81 RW; Torbjørn Heggem 77 CB; Roberto Piccoli 76 ST; Nikola Moro 77 CM; Emil Holm 78 RB; Tommaso Pobega 76 CM; Samuel Mbangula 74 LW; Oussama El Azzouzi 74 DM; Jens Odgaard 78 AM; Łukasz Skorupski 79 GK; Martin Vitík 76 CB; Nicolò Cambiaghi 77 LW; Charalampos Lykogiannis 75 LB; Remo Freuler 79 DM; Santiago Castro 77 ST; Jhon Lucumí 81 CB; Thijs Dallinga 76 ST; Jonathan Rowe 77 LW; Ciro Immobile 76 ST; Nadir Zortea 76 RB
sge: Mario Götze 78 AM; Ritsu Dōan 81 RW; Younes Ebnoutalib 75 ST; Can Uzun 79 AM 88; Raphael Onyedika 80 DM; Robin Koch 81 CB; Noah Atubolu 81 GK 86; Jonathan Burkardt 80 ST; Farès Chaïbi 78 AM; Ayoube Amaimouni 68 RW 80; Oscar Højlund 76 CM 84; Ansgar Knauff 78 RW; Nnamdi Collins 76 CB 84; Keita Kosugi 72 CB; Timothy Chandler 68 RB; Noël Aséko 70 DM 82; Kauã Santos 76 GK 84; Elias Baum 72 LB; Ellyes Skhiri 79 DM; Rasmus Kristensen 78 RB; Jean-Mattéo Bahoya 77 LW 85; Tuta 78 CB; Arthur Theate 79 CB; Hugo Larsson 78 CM 85; Michy Batshuayi 74 ST; Aurèle Amenda 76 CB
wob: Christian Eriksen 78 CM; Joakim Mæhle 77 RB; Maximilian Arnold 79 CM; Kento Shiogai 72 ST; Aster Vranckx 76 CM; Mattias Svanberg 78 CM; Fraser Hornby 70 ST; Timon Wellenreuther 75 GK; Vini Souza 77 DM; Alexander Bernhardsson 72 LW; Fabian Reese 76 LW; Robert Glatzel 74 ST; Jonas Adjetey 74 CB; Saël Kumbedi 72 RB; Bence Dárdai 73 CM; Yannick Gerhardt 74 LB; Muhammed Damar 70 CM; Elvis Rexhbeçaj 72 CM; Lovro Majer 78 AM; Denis Vavro 77 CB; Mohammed Amoura 80 ST; Konstantinos Koulierakis 76 CB; Kamil Grabara 77 GK; Patrick Wimmer 76 RW
nic: Axel Witsel 72 DM; Elye Wahi 76 ST; Mohamed Amoura 80 ST; Moïse Bombito 80 CB; Niels Nkounkou 77 LB; Morgan Sanson 76 CM; Mohamed Abdelmonem 76 CB; Jonathan Clauss 78 RB; Hicham Boudaoui 78 CM; Sofiane Diop 81 AM; Ali Abdi 75 LB; Antoine Mendy 72 CB; Salis Abdul Samed 76 DM; Yehvann Diouf 77 GK; Youssouf Ndayishimiye 77 DM; Nathan Ngoumou 70 RW; Gauthier Hein 71 AM; Isak Jansson 72 LW; Terem Moffi 77 ST; Tanguy Ndombele 76 CM; Dante 72 CB; Tom Louchet 72 CM; Jérémie Boga 77 LW; Kevin Carlos 74 ST
rcs: Giovanni Reyna 76 AM; Dário Essugo 75 DM 84; Filip Jörgensen 78 GK; Omari Kellyman 70 CM; Deivid Washington 74 ST; Gessime Yassine 69 RW; Conrad Harder 76 ST 84; Joaquín Panichelli 77 ST; Genesis Antwi 66 CB; Samir El Mourabet 70 AM; Sam Amo-Ameyaw 70 RW; Sékou Mara 72 ST; Jeyland Mitchell 72 CB; Jacobo Ortega 68 LW; Maxi Oyedele 69 CM; Sebastian Nanasi 76 LW; Oso 70 CB; Karim Coulibaly 68 CB; Ismaël Doukouré 77 CB; Julio Enciso 77 AM; Guéla Doué 76 RB; Emanuel Emegha 76 ST; Valentín Barco 77 LB; Mike Penders 72 GK 84; Abdoul Ouattara 72 RW; Mathis Amougou 72 CM; Ben Chilwell 76 LB; Diego Moreira 76 RW
hil: Ollie Watkins 81 ST; Gabriel Martinelli 81 LW; Crysencio Summerville 78 RW; Théo Hernandez 83 LB; Rúben Neves 82 DM; Sergej Milinković-Savić 82 CM; Yassine Bounou 82 GK; Kalidou Koulibaly 79 CB; Salem Al-Dawsari 78 LW; Mohamed Kanno 76 CM; Yusuf Akçiçek 72 CB 85; Nasser Al-Dawsari 74 DM; Mohammed Al-Owais 73 GK; Hassan Al-Tambakti 76 CB; Sultan Mandash 72 RB; Ali Lajami 72 CB; Aleksandar Mitrović 80 ST; Malcom 80 RW; Darwin Núñez 81 ST; Marcos Leonardo 74 ST; Kaio César 74 RW; Moteb Al-Harbi 73 LB
nas: Cristiano Ronaldo 80 ST; João Félix 80 AM; Sadio Mané 80 LW; Kingsley Coman 80 RW; Samú Costa 77 CM; Iñigo Martínez 80 CB; Mohamed Simakan 80 CB; Ângelo Gabriel 74 RW; Bento 79 GK; Abdullah Al-Hamdan 72 ST; Nawaf Al-Aqidi 74 GK; Abdulelah Al-Amri 75 CB; Sultan Al-Ghannam 73 RB; Abdullah Al-Khaibari 72 CM; Abdulrahman Ghareeb 73 LW; Nawaf Boushal 72 LB; Ayman Yahya 73 RW; Hayder Abdulkareem 68 DM; Marcelo Brozović 80 DM; Wesley 78 LW
itt: Georginio Wijnaldum 74 CM; Steven Bergwijn 79 RW; Richard Ríos 79 CM; Youssef En-Nesyri 80 ST; Houssem Aouar 79 AM; George Ilenikhena 70 ST 82; Danilo Pereira 74 CB; Predrag Rajković 79 GK; Jan-Carlo Simić 74 CB; Roger Fernandes 72 LW; Mukhtar Ali 72 CM; Dion Lopy 74 DM; Saleh Al-Shehri 72 ST; Mahamadou Doumbia 72 AM; Faris Abdi 70 CB; Marwan Al-Sahafi 70 LW; Hassan Kadesh 69 RB; Talal Haji 66 RW 78; Karim Benzema 80 ST; N'Golo Kanté 80 DM; Fabinho 78 DM; Moussa Diaby 82 RW
ahl: Ivan Toney 81 ST; Francisco Trincão 81 RW; Édouard Mendy 80 GK; Merih Demiral 80 CB; Roger Ibañez 80 CB; Eduard Spertsyan 76 AM; Galeno 81 LW; Valentin Atangana 72 CM; Firas Al-Buraikan 76 ST; Matheus Gonçalves 70 RW; Artem Bondarenko 76 CM; Abubacarr Sedi Kinteh 66 CB; Ali Majrashi 72 RB; Ziyad Al-Johani 72 CM; Abdullah Radif 70 ST; Zakaria Hawsawi 71 CB; Saleh Abu Al-Shamat 68 DM; Abdulrahman Al-Sanbi 68 GK; Riyad Mahrez 81 RW; Enzo Millot 80 AM; Franck Kessié 80 CM
mia: Lionel Messi 85 RW; Luis Suárez 76 ST; Rodrigo De Paul 78 CM; Sergio Busquets 74 DM; Jordi Alba 74 LB
lag: Riqui Puig 77 CM; Marco Reus 75 AM
zen: Claudinho 78 AM; Wendel 77 CM; Luciano Gondou 76 ST
ran: Jack Butland 77 GK; James Tavernier 76 RB; Nicolas Raskin 77 CM
cel: Kasper Schmeichel 77 GK; Callum McGregor 77 CM; Daizen Maeda 79 LW; Cameron Carter-Vickers 78 CB; Arne Engels 76 CM; Reo Hatate 78 CM; Kyogo Furuhashi 76 ST
sha: Pedrinho 77 CM; Kauã Elias 75 ST 84; Marlon Gomes 76 CM; Eguinaldo 74 LW; Artem Bondarenko 76 CM; Heorhiy Sudakov 80 AM; Mykola Matviyenko 78 CB; Dmytro Riznyk 77 GK
fer: Barnabás Varga 76 ST; Dénes Dibusz 75 GK; Mohammad Abu Fani 75 CM; Ibrahim Cissé 74 CB
dzg: Dominik Livaković 78 GK; Marko Pjaca 75 LW; Arijan Ademi 72 DM; Martin Baturina 79 AM
zen: Nino 76 CB; Andrey Mostovoy 76 LW
"""


def _parse():
    out = {}
    for line in _RAW.strip().splitlines():
        if ':' not in line:
            continue
        club, rest = line.split(':', 1)
        for item in rest.split(';'):
            toks = item.strip().split()
            if len(toks) < 3:
                continue
            pot = None
            if len(toks) >= 4 and toks[-1].isdigit() and toks[-2] in ('GK', 'RB', 'CB', 'LB', 'DM', 'CM', 'AM', 'RW', 'LW', 'ST'):
                pot = int(toks[-1])
                toks = toks[:-1]
            pos, ovr = toks[-1], int(toks[-2])
            name = ' '.join(toks[:-2])
            out[f'{club.strip()}:{name}'] = (ovr, pos) + ((pot,) if pot else ())
    return out


OVERRIDES = _parse()
